// 📖 Hints: ./hints.md
// 📖 Reference: ./reference.cpp

/*
 * LeetCode Problem 389: Find the Difference
 * Difficulty: Easy
 * Tags: Bit Manipulation, Hash Table, String, Sorting
 *
 * Problem Description:
 * You are given two strings `s` and `t`.
 * 
 * String `t` is generated by random shuffling string `s` and then add one more
 * letter at a random position.
 * 
 * Return the letter that was added to `t`.
 * 
 * 
 * 
 * **Example 1:**
 * 
 *     
 *     
 *     **Input:** s = "abcd", t = "abcde"
 *     **Output:** "e"
 *     **Explanation:** 'e' is the letter that was added.
 *     
 * 
 * **Example 2:**
 * 
 *     
 *     
 *     **Input:** s = "", t = "y"
 *     **Output:** "y"
 *     
 * 
 * 
 * 
 * **Constraints:**
 * 
 *   * `0 <= s.length <= 1000`
 *   * `t.length == s.length + 1`
 *   * `s` and `t` consist of lowercase English letters.
 * 
 * 
 *
 * Link: https://leetcode.com/problems/find-the-difference/
 */

#include <iostream>
#include <vector>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <map>
#include <set>
#include <queue>
#include <stack>
#include <algorithm>
#include <climits>
#include <cmath>

using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
        
    }
};

// ==================== Test Harness ====================
// Modify this section to test your solution locally

int main() {
    Solution solution;

    // Example test cases from LeetCode:
    // Test case 1: "abcd"
    // Test case 2: "abcde"
    // Test case 3: ""
    // Test case 4: "y"

    // TODO: Add your test cases here
    // Example:
    // vector<int> nums = {1, 2, 3};
    // auto result = solution.yourMethod(nums);
    // cout << "Result: " << result << endl;

    cout << "Tests completed!" << endl;
    return 0;
}
